version: '3.4'

services:
  gestaoequipamentospetroliferos:
    image: gestaoequipamentospetroliferos
    build:
      context: .
      dockerfile: src/GestaoEquipamentosPetroliferos/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw